version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - LOGSTASH_HOST=192.168.126.130
      - LOGSTASH_PORT=5000
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend
    restart: always
